# Generated by Django 5.1.4 on 2025-05-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='gitlink',
        ),
        migrations.AddField(
            model_name='project',
            name='projectlink',
            field=models.URLField(blank=True),
        ),
    ]
